create database Ananthi;
show databases;
create table student(name char(25),roll_no varchar(8),sex char(1),dept char(5));
insert into student values("ananthi","15bee084","f","eee");
insert into student values("ananthi","15bee084","f","eee");
insert into student values("sudha","15bee085","f","eee");
select * from student;
select count(*) from student;
desc student;
select distinct * from student;
desc student;
